version: '3'
services:

  web-client:
    build: ./web-client
    container_name: climat_web_client
    command: yarn start
    volumes:
      - ./web-client:/web-client

  server:
    build: ./server
    container_name: climat_server
    command: rails s -b 0.0.0.0
    volumes:
      - ./server:/server
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: climat_db
    environment:
      POSTGRES_USER: climat
      POSTGRES_PASSWORD: climat
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - 3000:3000
    volumes:
      - ./server/config/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./server/log/nginx.log:/var/log/nginx/nginx.log
    depends_on:
      - server
      - web-client

volumes:
  postgres:
